services:
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - 8686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  orchestrator:
    image: dflipse/ds-fit-controller:latest
    ports:
      - "5050:5000"
    environment:
      - PROXY_LIST=proxy1:8050,proxy2:8050,proxy3:8050
      - OTEL_SERVICE_NAME=orchestrator
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4137

  proxy1:
    image: dflipse/ds-fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://localhost:8090
      - ORCHESTRATOR_HOST=orchestrator:5000
      - CONTROLLER_PORT=8050
      - USE_OTEL=true
      - OTEL_SERVICE_NAME=proxy1
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4137

  proxy2:
    image: dflipse/ds-fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://localhost:8090
      - ORCHESTRATOR_HOST=orchestrator:5000
      - CONTROLLER_PORT=8050
      - USE_OTEL=true
      - OTEL_SERVICE_NAME=proxy2
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4137
  proxy3:
    image: dflipse/ds-fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://localhost:8090
      - ORCHESTRATOR_HOST=orchestrator:5000
      - CONTROLLER_PORT=8050
      - USE_OTEL=true
      - OTEL_SERVICE_NAME=proxy3
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4137
